# to enable: add NPM_token secret and activate main branch
name: Build and publish

on:
  push:
    branches:
      # - main
      - some-non-existing-branch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 💼
        uses: actions/checkout@v4

      - name: Install Node.js 🧩
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for critical vulnerabilities 🔎
        run: npm audit --audit-level critical --omit=dev

      - name: Install dependencies 📦
        run: npm ci

      - name: Run tests 🧪
        run: npm test

      - name: Build 🏗️
        run: npm run build

      - name: Add license notice 📜
        run: npm run license

      - name: Set up NPM 🔑
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish 🚀
        run: npm publish --access public
